### ISSUE TITLE
LoadError: undefined symbol: Init_jemalloc

### ISSUE THREAD

**Issue by dalezak** [gaffneyc/heroku-buildpack-jemalloc#10]
I'm trying to deploy to Heroku using Ruby `2.5.1`, but getting the following error:
```
remote: -----> Detecting rake tasks
remote:
remote:  !
remote:  !     Could not detect rake tasks
remote:  !     ensure you can run `$ bundle exec rake -P` against your app
remote:  !     and using the production group of your Gemfile.
remote:  !     rake aborted!
remote:  !     LoadError: /tmp/build_35b27e3a334f16038d45bd4e05d69cce/vendor/bundle/ruby/2.5.0/gems/jemalloc-1.0.1/lib/jemalloc.so: undefined symbol: Init_jemalloc - /tmp/build_35b27e3a334f16038d45bd4e05d69cce/vendor/bundle/ruby/2.5.0/gems/jemalloc-1.0.1/lib/jemalloc.so
remote:  !     /tmp/build_35b27e3a334f16038d45bd4e05d69cce/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
remote:  !     /tmp/build_35b27e3a334f16038d45bd4e05d69cce/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
remote:  !     /tmp/build_35b27e3a334f16038d45bd4e05d69cce/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
remote:  !     /tmp/build_35b27e3a334f16038d45bd4e05d69cce/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
remote:  !     /tmp/build_35b27e3a334f16038d45bd4e05d69cce/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
remote:  !     /tmp/build_35b27e3a334f16038d45bd4e05d69cce/vendor/bundle/ruby/2.5.0/gems/bundler-2.0.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
remote:  !     /tmp/build_35b27e3a334f16038d45bd4e05d69cce/vendor/bundle/ruby/2.5.0/gems/bundler-2.0.1/lib/bundler/runtime.rb:76:in `each'
remote:  !     /tmp/build_35b27e3a334f16038d45bd4e05d69cce/vendor/bundle/ruby/2.5.0/gems/bundler-2.0.1/lib/bundler/runtime.rb:76:in `block in require'
remote:  !     /tmp/build_35b27e3a334f16038d45bd4e05d69cce/vendor/bundle/ruby/2.5.0/gems/bundler-2.0.1/lib/bundler/runtime.rb:65:in `each'
remote:  !     /tmp/build_35b27e3a334f16038d45bd4e05d69cce/vendor/bundle/ruby/2.5.0/gems/bundler-2.0.1/lib/bundler/runtime.rb:65:in `require'
remote:  !     /tmp/build_35b27e3a334f16038d45bd4e05d69cce/vendor/bundle/ruby/2.5.0/gems/bundler-2.0.1/lib/bundler.rb:114:in `require'
remote:  !     /tmp/build_35b27e3a334f16038d45bd4e05d69cce/config/application.rb:5:in `<top (required)>'
remote:  !     /tmp/build_35b27e3a334f16038d45bd4e05d69cce/Rakefile:4:in `require_relative'
remote:  !     /tmp/build_35b27e3a334f16038d45bd4e05d69cce/Rakefile:4:in `<top (required)>'
remote:  !     /tmp/build_35b27e3a334f16038d45bd4e05d69cce/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/lib/rake/rake_module.rb:29:in `load'
remote:  !     /tmp/build_35b27e3a334f16038d45bd4e05d69cce/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/lib/rake/rake_module.rb:29:in `load_rakefile'
remote:  !     /tmp/build_35b27e3a334f16038d45bd4e05d69cce/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:703:in `raw_load_rakefile'
remote:  !     /tmp/build_35b27e3a334f16038d45bd4e05d69cce/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:104:in `block in load_rakefile'
remote:  !     /tmp/build_35b27e3a334f16038d45bd4e05d69cce/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
remote:  !     /tmp/build_35b27e3a334f16038d45bd4e05d69cce/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:103:in `load_rakefile'
remote:  !     /tmp/build_35b27e3a334f16038d45bd4e05d69cce/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:82:in `block in run'
remote:  !     /tmp/build_35b27e3a334f16038d45bd4e05d69cce/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
remote:  !     /tmp/build_35b27e3a334f16038d45bd4e05d69cce/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
remote:  !     /tmp/build_35b27e3a334f16038d45bd4e05d69cce/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
remote:  !     vendor/bundle/bin/rake:29:in `load'
remote:  !     vendor/bundle/bin/rake:29:in `<main>'
remote:  !     Push rejected, failed to compile Ruby app.
```
I followed the instructions on https://elements.heroku.com/buildpacks/gaffneyc/heroku-buildpack-jemalloc, any ideas?

**Comment by gaffneyc** [comment]
It looks like you have the [jemalloc gem](https://rubygems.org/gems/jemalloc) in your bundle which is probably conflicting with the newer version that is provided by the buildpack. I'm not sure which version the gem supplies but it hasn't seen a new release in 4 years.

Try removing it from your Gemfile and let me know if that fixes things.

**Comment by dalezak** [comment]
@gaffneyc that worked! Thanks 👍
